### PR TITLE
Fix Recipe types declaration

### LINKED ISSUE #349: New Recipe from buffer throws "path" error
Here's my code:

```
const pdfBuffer = Buffer.from( 'base64string...', 'base64' )
const newBuffer = await new Promise<Buffer>( async ( res ) => {
    const pdfDoc = new Recipe( pdfBuffer, {
        author: 'test',
        title: 'pdf test',
        subject: 'test on muhammara'
    } )
    pdfDoc.endPDF( buffer => res( buffer ) )
} )
```
Runnint this code I get the following error:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Object
      at Object.openSync (node:fs:593:10)
      at Object.writeFileSync (node:fs:2249:35)
      at Recipe.endPDF (path/to/backend/node_modules/muhammara/lib/Recipe.js:262:10)
      at newBuffer (path/to/backend/build/apps/api/index.js:66:16)
      at new Promise (<anonymous>)
      at path/to/backend/build/apps/api/index.js:60:29 {
    code: 'ERR_INVALID_ARG_TYPE'
 }
 Node.js v18.16.0
```

Reading [docs](https://github.com/julianhille/MuhammaraJS#create-a-new-pdf-as-a-buffer) i think there's an error on it because I can't add `null` as seccond param while creating `new Recipe`.

### PR DESCRIPTION
**Pull request by luicfrr**
Also closes #349

### CODE REVIEW

**Comment by julianhille** [comment]
Please run prettier linting tool

**Comment by nonam4** [comment]
Take a look now, I think now lint is correct

**Comment by luicfrr** [comment]
Ok, I don't know what is wrong now :sweat:
I've cloned whole repo on my machine, run `npx prettier --write .` command and also run `npx prettier -c ./` command and I got no lint error.

Can you please take a look?

**Comment by julianhille** [comment]
Currently my laptop is broken and so I'm unable tohelp or investigate. Will take some days

**Comment by julianhille** [comment]
Have add this through another PR. Thank you

**Pull request closed without merging**
