### PR TITLE
Ignore extra data above the header and below the footer in PDF Parser

### LINKED ISSUE #211: `Unable to start parsing PDF file` error for PDFs from certain producers
We have noticed that PDFs generated by the following producers cannot be understood by `muhamarra`:
1. `StreamServe Communication Server 16.4.0 GA Build`
2. `macOS Version 11.2.3 (Build 20D91) Quartz PDFCo`

In both cases, the PDFs load in other readers (e.g. Adobe Reader).

I do not want to post examples publicly, since they contain personal information, but I can send them privately.

To reproduce:
```js
muhammara.createReader('input.pdf') // TypeError: Unable to start parsing PDF file

muhammara
  .createWriter('output.pdf')
  .appendPDFPagesFromPDF('input.pdf') // TypeError: unable to append page, make sure it's fine
```

### PR DESCRIPTION
**Pull request by mhassan1**
This PR enhances `PDFParser.cpp` to be more lenient about data before the header and after the footer: when it encounters data like that, it ignores it, which is consistent with how other PDF parsers act.

The change involves adding a `MoveStartPosition` method to relevant stream classes; when called, this will set a pointer to a different start position in the stream (it starts at 0). Other methods like `GetCurrentPosition` and `SetPosition` will get and set the position relative to the new start position.

During PDF parsing, we will look for the `%PDF-` header, ignoring anything before it, until we find it (or we reach the end of the stream); at that point, we will move the start position to the start of the header, which will be 0 in the case of a PDF that follows the spec, but will be non-zero, otherwise. Similarly, we will search for the `%%EOF` footer, ignoring anything after it, until we find it (or we reach the start of the stream).

Resolves https://github.com/julianhille/MuhammaraJS/issues/211.

### CODE REVIEW

**Comment by julianhille** [comment]
We should limit the amount of look ahead to the 1024 bytes mentioned in the docs otherwise this could be used to dos a service

**Comment by julianhille** [comment]
Sorry forgot: Thanks for the pr so far.

**Comment by mhassan1** [comment]
I've added a check for `mStream->GetCurrentPosition() < 1024` in the `while` condition.

**Review by julianhille — DISMISSED** [review]
LGTM. im unsure if we really need all those position transformations. my first guess on implementing was to "just skip unitl" but this does not seem possible here. Thank you

**Comment by mhassan1** [comment]
I see a build failure for `musl`: https://github.com/julianhille/MuhammaraJS/actions/runs/3297775311/jobs/5440562834. @julianhille Do you know how to fix that?

**Comment by julianhille** [comment]
You can safely ignore these for now. That is because you added the pr and then it does not use secrets to download musl Container.

**Comment by mhassan1** [comment]
@julianhille I just resolved a conflict in `CHANGELOG.md`. This is ready for review again.

**Review by julianhille — APPROVED** [review]

**Comment by mhassan1** [comment]
@julianhille What is left before we can merge this?

**Comment by julianhille** [comment]
Nothing, i use my administrator super powers and merge this now. Thank you for your contribution

**Pull request merged**
