### PR TITLE
Add arm64 for musl builds

### LINKED ISSUE #251: add musl with arm64 to the build matrix
We should prebuild musl with arm64 architecture.
M1s are on the rise and arm64 will be more and more on the market.
If someone now uses an alpine base container compiling is always needed, which costs time and resources, as musl / arm64 combination is not pre build

### PR DESCRIPTION
**Pull request by julianhille**
Fixes #251

### CODE REVIEW

**Comment by julianhille** [comment]
https://github.com/julianhille/MuhammaraJS/suites/9904368270/artifacts/478676608 
@hilmanski would you be able to test these binaries in your alpine machine?

**Comment by hilmanski** [comment]
Hi @julianhille thanks for making this.
Apologize I'm not expert on the arm64/musl things. Need more detail guide what I can help here.

When I download it, it shows the node targ.gz file.

any step by step what should I do to test it?

**Comment by julianhille** [comment]
ill try to upload a beta onto npm with this changes, you would need to change your version to this beta and then fully rebuild your docker container.
It then should work AND would not need to compile.

**Comment by julianhille** [comment]
3.6.0-beta.1 please try this version and rebuild your container.

**Comment by hilmanski** [comment]
HI @julianhille 
I tried to run this on prev plain docker sample you provided
In case anyone need reference: https://github.com/hilmanski/test-muhammara-arm64-musl

Current output. Guess this is the intended result?
Screen Shot 2022-12-27 at 06 24 58

**Comment by julianhille** [comment]
Could you provide the build log? I'd like to see if it compiles or downloads the prebuilt.

**Comment by hilmanski** [comment]
Here's the log
https://app.warp.dev/block/48mCeLGiaVPRtSgBrwXq55

**Comment by julianhille** [comment]
That looks awesome.
Thank you very muchm

**Comment by hilmanski** [comment]
> That looks awesome. Thank you very muchm

happy to help. 
Appreciate your effort as well :) have a good day!

**Pull request merged**
