### PR TITLE
Build musl/musl-arm with node 20

### PR DESCRIPTION
**Pull request by guillaumelecerf**

### CODE REVIEW

**Comment by julianhille** [comment]
Thanks fornthe controbution. Mind adding a Changelogo entry?

**Comment by guillaumelecerf** [comment]
Here it is (hoping the changelog message, as the commit one, is clear enough).
I was waiting for the CI to run to confirm that it was actually buildable, but it seems broken (missing docker secrets).

**Comment by julianhille** [comment]
> Here it is (hoping the changelog message, as the commit one, is clear enough). I was waiting for the CI to run to confirm that it was actually buildable, but it seems broken (missing docker secrets).

Yes. Thisnis because These are my docker Hub credentiald which are Not available to Public runs. Let me try to fix it

**Comment by guillaumelecerf** [comment]
Thanks!
Would you please mind publishing the musl/musl-arm 4.0.0 build artefacts?

**Comment by julianhille** [comment]
> Thanks! Would you please mind publishing the musl/musl-arm 4.0.0 build artefacts?

i wont push any updates to a 4.0.0 version anymore there will be a 4.1.0 (soom[TM])

**Comment by tommyk** [comment]
> > Thanks! Would you please mind publishing the musl/musl-arm 4.0.0 build artefacts?
> 
> i wont push any updates to a 4.0.0 version anymore there will be a 4.1.0 (soom[TM])

how long are you thinking before releasing 4.1.0?  i am currently having to wait excessive times for this to be built locally, and do special github action caching to try and avoid this build taking ~6 minutes.

**Comment by julianhille** [comment]
4.1.0 Has been released

**Pull request merged**
